### ISSUE TITLE
Get rid of 'Overview'

### ISSUE THREAD

**Issue by chucker** [trenz-gmbh/trenz-docs#4]
* Only expand/collapse tree node when clicking the chevron
* When clicking the title, show the overview instead
* Remove 'Overview' as a separate page

**Comment by ricardoboss** [comment]
What happens when clicking the title and no overview is available?

Three options:

- keep the current behavior (show 404)
- do nothing instead (node would be like text instead of a button and the chevron would expand the children)
- use the whole node as the expand button instead (clicking the node OR the chevron expands the children)

**Comment by chucker** [comment]
>What happens when clicking the title and no overview is available?

ADO shows a… weird message:

![image](https://user-images.githubusercontent.com/20194/179702715-6cb91c19-1f77-46b4-962f-b2f38933a434.png)

But ADO also expands/collapses when clicking the title.

So maybe we _should_ always expand/collapse, but simply show an empty page if there's no content.

>keep the current behavior (show 404)

I think that's bad. It has "the user did something wrong" vibes.

So, now I'm leaning towards:

* always expand/collapse, as is already the case
* always show a link
* show overview if it exists
* if it doesn't exist, show the breadcrumb, but nothing underneath?

**Comment by ricardoboss** [comment]
Personally, I'm not a fan of always expand/collapse, because then the button suddenly has two functions: open the overview page and expand/collapse. What if I have already expanded the subtree and want to view the overview again without collapsing the subtree?

I think two distinct actions should have two distinct buttons.

**Comment by chucker** [comment]
I definitely don’t like the current 404 behavior, in any case.

**Comment by ricardoboss** [comment]
We agreed to implement a very similar navigation tree as Azure DevOps has:

```
if the node is expanded and the node is currently active
  collapse the children
else if the node is expanded and not currently active
  if the node has content            // our custom logic, ADO shows a 'this is a folder message'
    navigate to the node
else if the node is not expanded and currently active
  expand the children
else
  if the node has content
    navigate to the node
  expand the children
```

The API only needs to tell the frontend whether a specific node has content or not.
